.Dd $Mdocdate$
.Dt XCALICON 1
.Os
.Sh NAME
.Nm xcalicon
.Nd show date and time as an iconified X11 window
.Sh SYNOPSIS
.Nm
.Op Fl d Ar display
.Sh DESCRIPTION
.Nm
shows the current date as an icon, and the time as the icon's title.
Un-iconifying the program shows the same icon in a small window.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Use a different X11 display.
.El
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
